config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :buyer_products
  resources :sellers
  resources :buyers
  resources :profiles
  devise_for :users
  root 'home#page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer_product.rb
class BuyerProduct < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/controllers/buyer_products_controller.rb
class BuyerProductsController < ApplicationController
  before_action :set_buyer_product, only: [:show, :edit, :update, :destroy]

  # GET /buyer_products
  # GET /buyer_products.json
  def index
    @buyer_products = BuyerProduct.all
  end

  # GET /buyer_products/1
  # GET /buyer_products/1.json
  def show
  end

  # GET /buyer_products/new
  def new
    @buyer_product = BuyerProduct.new
  end

  # GET /buyer_products/1/edit
  def edit
  end

  # POST /buyer_products
  # POST /buyer_products.json
  def create
    @buyer_product = BuyerProduct.new(buyer_product_params)

    respond_to do |format|
      if @buyer_product.save
        format.html { redirect_to @buyer_product, notice: 'Buyer product was successfully created.' }
        format.json { render :show, status: :created, location: @buyer_product }
      else
        format.html { render :new }
        format.json { render json: @buyer_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyer_products/1
  # PATCH/PUT /buyer_products/1.json
  def update
    respond_to do |format|
      if @buyer_product.update(buyer_product_params)
        format.html { redirect_to @buyer_product, notice: 'Buyer product was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer_product }
      else
        format.html { render :edit }
        format.json { render json: @buyer_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyer_products/1
  # DELETE /buyer_products/1.json
  def destroy
    @buyer_product.destroy
    respond_to do |format|
      format.html { redirect_to buyer_products_url, notice: 'Buyer product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer_product
      @buyer_product = BuyerProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_product_params
      params.require(:buyer_product).permit(:buyer_id, :product_id)
    end
end

app/helpers/buyer_products_helper.rb
module BuyerProductsHelper
end

app/views/buyer_products/_form.html.erb
<%= simple_form_for(@buyer_product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :buyer %>
    <%= f.association :product %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buyer_products/edit.html.erb
<h1>Editing Buyer Product</h1>

<%= render 'form', buyer_product: @buyer_product %>

<%= link_to 'Show', @buyer_product %> |
<%= link_to 'Back', buyer_products_path %>

app/views/buyer_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buyer Products</h1>

<table>
  <thead>
    <tr>
      <th>Buyer</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyer_products.each do |buyer_product| %>
      <tr>
        <td><%= buyer_product.buyer %></td>
        <td><%= buyer_product.product %></td>
        <td><%= link_to 'Show', buyer_product %></td>
        <td><%= link_to 'Edit', edit_buyer_product_path(buyer_product) %></td>
        <td><%= link_to 'Destroy', buyer_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer Product', new_buyer_product_path %>

app/views/buyer_products/new.html.erb
<h1>New Buyer Product</h1>

<%= render 'form', buyer_product: @buyer_product %>

<%= link_to 'Back', buyer_products_path %>

app/views/buyer_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buyer:</strong>
  <%= @buyer_product.buyer %>
</p>

<p>
  <strong>Product:</strong>
  <%= @buyer_product.product %>
</p>

<%= link_to 'Edit', edit_buyer_product_path(@buyer_product) %> |
<%= link_to 'Back', buyer_products_path %>